# Generated by Django 5.1.1 on 2024-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('district', 'sector', 'cell', 'village'), name='unique_location_combination'),
        ),
    ]
