# Generated by Django 5.1.1 on 2024-09-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_residence_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.DateField(max_length=8),
        ),
    ]
