# Generated by Django 5.1.1 on 2024-09-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_schedule_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='week',
            field=models.CharField(max_length=8),
        ),
    ]
