# Generated by Django 5.1.1 on 2024-09-13 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_schedule_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='plate',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Plate number needd to be formated like AAA 000 A', regex='^[A-Z]{3} [0-9]{3} [A-Z]$')]),
        ),
    ]
