# Generated by Django 5.1.1 on 2024-09-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_schedule_day'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('schedule', 'client'), name='unique_collection_combination'),
        ),
    ]
