# Generated by Django 5.1.1 on 2024-09-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_collection_unique_collection_combination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
    ]
